### ISSUE TITLE
All files that are uploaded with ep-staging should be chowned to scootr-www user.

### ISSUE THREAD

**Issue by terjekrogstad** [tagstudio/generator-ep#13]
Thought this was done by grunt-ssh but it seems to fail when you start a new project. The user from scootr config is set as owner of file.

**Comment by ToreKlevenberg** [comment]
Det er ingen scootr-www bruker, det er bare en gruppe.
Er det egentlig et problem?  De er jo eid av gruppen, så andre i gruppen kan vel skrive over?

**Comment by terjekrogstad** [comment]
Ja, mente nok chowned til scootr-www gruppe. Husker ikke når det skjedde, men kan jo kanskje gå over  Gruntfile og se at alle ssh-oppgavene gjør dette... Andre i gruppen får skrevet over så lenge man har rettigheter 775

**Comment by ToreKlevenberg** [comment]
Ser iallefall ut til å gjelde moduler i lib katalogen
